# Generated by Django 3.0.5 on 2020-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('role', models.CharField(choices=[('stu', 'student'), ('org', 'organization'), ('schl', 'school')], max_length=50)),
            ],
        ),
    ]
